"""add firebase_uid and footprint_data to sessions

Revision ID: 7e72306dc22b
Revises: be623c9a6950
Create Date: 2026-06-21 00:38:40.939298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e72306dc22b'
down_revision: Union[str, Sequence[str], None] = 'be623c9a6950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.add_column('sessions', sa.Column('footprint_data', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'sessions', 'users', ['firebase_uid'], ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'footprint_data')
    op.drop_column('sessions', 'firebase_uid')
    # ### end Alembic commands ###
